### ISSUE TITLE
webdav Read timed out

### ISSUE THREAD

**Issue by Strubbl** [EpocDotFr/webtodotxt#29]
Today, i rebuilt the docker container with all updated components (alpine updates, python dependency updates etc) and it stopped working. I always get a connection timeout error. 

I am using WebdavAuth. It worked until today before i updated.

The only python requirement which got recently updated is https://pypi.org/project/Flask-HTTPAuth/#history
But maybe some python core dependency got updated too?

With two other clients, the webdav (with nextcloud) works fine. Even Simpletask app with Nextcloud support still works fine.

Do you have any idea how i can recover from this error?

My error message is:

```
[2018-06-06 20:41:01,478] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/local/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cloud.test.de', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/webdav3/client.py", line 70, in _wrapper
    res = fn(self, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/webdav3/client.py", line 273, in check
    response = self.execute_request(action='check', path=urn.quote())
  File "/usr/local/lib/python3.6/site-packages/webdav3/client.py", line 164, in execute_request
    data=data
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cloud.test.de', port=443): Read timed out. (read timeout=30)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/site-packages/flask_httpauth.py", line 85, in decorated
    password = self.get_password_callback(auth.username)
  File "./hooks.py", line 21, in get_password
    return backend.retrieve_password(username)
  File "./auth_backends.py", line 49, in retrieve_password
    if client.check(self.config['path'].format(username=username)):
  File "/usr/local/lib/python3.6/site-packages/webdav3/client.py", line 74, in _wrapper
    raise ConnectionException(re)
webdav3.exceptions.ConnectionException: HTTPSConnectionPool(host='cloud.test.de', port=443): Read timed out. (read timeout=30)
[pid: 15|app: 0|req: 6/8] 172.17.0.1 () {48 vars in 998 bytes} [Wed Jun  6 20:40:31 2018] GET / => generated 1594 bytes in 30114 msecs (HTTP/1.0 500) 2 headers in 100 bytes (1 switches on core 1)
[pid: 16|app: 0|req: 3/9] 172.17.0.1 () {48 vars in 1019 bytes} [Wed Jun  6 20:41:01 2018] GET /todotxt-static/css/app.css => generated 8929 bytes in 2 msecs via sendfile() (HTTP/1.0 200) 8 headers in 301 bytes (0 switches on core 0)

```

**Comment by Strubbl** [comment]
new day, and the issue is gone.
sorry for the noise of this issue.
