### ISSUE TITLE
Logging in

### ISSUE THREAD

**Issue by 0xRoM** [EpocDotFr/webtodotxt#30]
Hi, after submitting correct user & password I get the error:

A server error occured! Please retry. If the error persists, please report an issue here.

in the console the following:
```
192.168.0.23 - - [08/Sep/2018 12:43:12] "GET / HTTP/1.1" 401 -
[2018-09-08 12:43:18,034] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_httpauth.py", line 97, in decorated
    password = self.get_auth_password(auth)
  File "/usr/local/lib/python2.7/dist-packages/flask_httpauth.py", line 83, in get_auth_password
    password = self.get_password_callback(auth.username)
  File "/opt/webtodotxt/hooks.py", line 19, in get_password
    backend = get_current_auth_backend()
  File "/opt/webtodotxt/helpers.py", line 31, in get_current_auth_backend
    return getattr(auth_backends, name)()
  File "/opt/webtodotxt/auth_backends.py", line 24, in __init__
    super(DictAuth, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj
```

**Comment by EpocDotFr** [comment]
Hello,

This project was written for Python 3.x. I see you're running Python 2.7.

Feel free to write a PR for Python 2.x compat (only if changes aren't too heavy).

**Comment by 0xRoM** [comment]
Thank you.
I have managed to get working using Python3
